commit

diff --git a/buildme b/buildme
--- a/buildme
+++ b/buildme
@@ -1,5 +1,9 @@
 #!/bin/bash
 
+# TODO: repl mode, inotifywait mode, implicit dependencies, implicit rules
+# configure, install, install-*, uninstall, all, test, dist (package), clean, doc,
+# check, installcheck
+
 # acceptable characters in function names: 1a*/~!@#%^*[]{}_-+=:.,?
 # unacceptable characters in function names: <>$`'"&();\|
 # to list all defined functions:
@@ -9,55 +13,61 @@ set -o nounset
 set -o errexit
 set -o pipefail
 shopt -s extglob
+shopt -s globstar
 
-# convert a indexed or associative array value to a properly quoted string
-tostring () {
-  local var="$(declare -p "$1")"
-  eval echo "${var/#declare -? $1=}"
+{ # utility functions
+
+  # convert a indexed or associative array value to a properly quoted string
+  tostring () {
+    local var="$(declare -p "$1")"
+    eval echo "${var/#declare -? $1=}"
+  }
+
+  # return the body of a defined function. Usage:
+  # . <(inline func_name)
+  inline () {
+    local fn="$(declare -f "$1")"
+    echo "${fn/#$1 \(\)}"
+  }
+
+  # split a string using a delimiter character
+  split () {
+    local IFS="$1"
+    set -- $2
+    local array=("$@")
+    tostring array
+  }
 }
 
-# return the body of a defined function. Usage:
-# . <(inline func_name)
-inline () {
-  local fn="$(declare -f "$1")"
-  echo "${fn/#$1 \(\)}"
-}
-
-# split a string using a delimiter character
-split () {
-  local IFS="$1"
-  set -- $2
-  local array=("$@")
-  tostring array
-}
-
-die () {
-  echo "$@" 1>&2
-  exit 1
-}
-
-warn () {
-  if (( log_level >= 1 )); then
+{ # logging functions
+  die () {
     echo "$@" 1>&2
-  fi
-}
+    exit 1
+  }
 
-log () {
-  if (( log_level >= 2 )); then
-    echo "$@" 1>&2
-  fi
-}
+  warn () {
+    if (( log_level >= 1 )); then
+      echo "$@" 1>&2
+    fi
+  }
 
-info () {
-  if (( log_level >= 3 )); then
-    echo "$@" 1>&2
-  fi
-}
+  log () {
+    if (( log_level >= 2 )); then
+      echo "$@" 1>&2
+    fi
+  }
 
-debug () {
-  if (( log_level >= 4 )); then
-    echo "$@" 1>&2
-  fi
+  info () {
+    if (( log_level >= 3 )); then
+      echo "$@" 1>&2
+    fi
+  }
+
+  debug () {
+    if (( log_level >= 4 )); then
+      echo "$@" 1>&2
+    fi
+  }
 }
 
 # rule function for determining sources for the target
@@ -66,63 +76,102 @@ depends () {
 }
 
 # find the most specific rule that matches the specified target
+# target rules get first priority, followed by pattern matching rules.
 buildme.findrule () {
+  local target="$1" fn rule file patrule
+
   # first get the list of rules:
   mapfile < <(compgen -A function)
-  for rule in "${MAPFILE[@]}"
-  do
-    case rule in
-      *:)
-
+  for fn in "${MAPFILE[@]}"; do
+    case "$fn" in
+      *[][*,?!@+{}]*:) # pattern matching rule
+        # A few pattern matching characters are not allowed in function names.
+        # Perform the following conversions as a workaround:
+        # {{->( }}->) ,,->|
+        # acceptable characters in function names: 0-9a-zA-Z*/~!@#%^*[]{}_-+=:.,?
+        if [[ ! -n "$patrule" ]]; then
+          fn="${fn%:}"
+          fn="${fn//\{\{/\(}"
+          fn="${fn//\}\}/\)}"
+          fn="${fn//,,/\|}"
+          pushd "$directory"
+          for file in $fn; do
+            if [[ "$target" -ef "$file" ]]; then
+              patrule="$fn"
+            fi
+          done
+          popd
+        fi
+        ;;
+      *::) # phony target rule
+        if [[ "$target" -ef "${fn%::}" ]]; then
+          rule="$fn"
+        fi
+        ;;
+      *:) # target rule
+        if [[ "$target" -ef "${fn%:}" ]]; then
+          rule="$fn"
+        fi
         ;;
     esac
-  done
-}
-
-buildme.update_check.pre.exists () {
-  [[ -e "$1" ]]
-}
-buildme.update_check.update.exists () {
-  [[ -e "$1" ]]
-}
-
-buildme.update_check.pre.checksum () {
-  [[ "${checksums["$1"]}" == $("$checksum_prog" "$1") ]]
-}
-buildme.update_check.update.checksum () {
-  if [[ "${checksums["$1"]}" == $("$checksum_prog" "$1") ]]; then  
-    return 1
+  done  
+  if [[ -n "$rule" ]]; then
+    echo "$rule"
+    return
+  elif [[ -n "$patrule" ]]; then
+    echo "$patrule"
+    return
   fi
-  checksums["$1"]="$("$checksum_prog" "$1")"
-  return 0
-}
-
-buildme.update_check.pre.mtime () {
-  local prev_max_mtime="${max_mtime:-0}"
-  max_mtime=0
   return 1
 }
-buildme.update_check.post.mtime () {
-  local target_mtime=$(stat -c %Y "$1")
-  if (( max_mtime < target_mtime )); then
-    max_mtime="$target_mtime"
-    # target doesn't need update
+
+{ # update checking functions
+
+  buildme.update_check.pre.exists () {
+    [[ -e "$1" ]]
+  }
+  buildme.update_check.update.exists () {
+    [[ -e "$1" ]]
+  }
+
+  buildme.update_check.pre.checksum () {
+    [[ "${checksums["$1"]}" == $("$checksum_prog" "$1") ]]
+  }
+  buildme.update_check.update.checksum () {
+    if [[ "${checksums["$1"]}" == $("$checksum_prog" "$1") ]]; then  
+      return 1
+    fi
+    checksums["$1"]="$("$checksum_prog" "$1")"
     return 0
-  fi
-  # target needs update
-  return 1
-}
-buildme.update_check.update.mtime () {
-  local updated_target_mtime=$(stat -c %Y "$1")
-  if (( updated_target_mtime < max_mtime )); then
-    # target was not updated
+  }
+
+  buildme.update_check.pre.mtime () {
+    local prev_max_mtime="${max_mtime:-0}"
+    max_mtime=0
     return 1
-  fi
-  if (( max_mtime < prev_max_mtime )); then
-    max_mtime="$prev_max_mtime"  
-  fi
-  # target successfully updated
-  return 0
+  }
+  buildme.update_check.post.mtime () {
+    local target_mtime="$(stat -c %Y "$1")"
+    if (( max_mtime < target_mtime )); then
+      max_mtime="$target_mtime"
+      # target doesn't need update
+      return 0
+    fi
+    # target needs update
+    return 1
+  }
+  buildme.update_check.update.mtime () {
+    local updated_target_mtime="$(stat -c %Y "$1")"
+    if (( updated_target_mtime < max_mtime )); then
+      # target was not updated
+      return 1
+    fi
+    if (( max_mtime < prev_max_mtime )); then
+      max_mtime="$prev_max_mtime"  
+    fi
+    # target successfully updated
+    return 0
+  }
 }
 
 # Build a target. By this time the target is known--there are no wildcards
@@ -135,11 +184,17 @@ buildme.build () {
 
   # find the best rule for this target
   local rule=$(buildme.findrule "$1") 
+  # determine if this rule is "phony"; we don't do an update check for these.
+  local phony
+  case "$rule" in 
+    *::) phony='true' ;;
+  esac
 
   # Check if the target needs updating. Some update methods can perform
   # this check before dependencies are built. Other methods, e.g. mtime
   # requires the dependencies to be looked up first.
-  if [[ -n "$(declare -F "buildme.update_check.pre.$update_check")" 
+  if [[ ! -n "$phony" && ! -n "$testmode"
+      && -n "$(declare -F "buildme.update_check.pre.$update_check")" 
       && . <(inline "buildme.update_check.pre.$update_check") ]]; then
     built["$*"]=0
     return 0 
@@ -158,25 +213,27 @@ buildme.build () {
   unset -v output
 
   # Check if the target needs updating. The mtime check happens here.
-  if [[ -n "$(declare -F "buildme.update_check.post.$update_check")" 
+  if [[ ! -n "$phony" && ! -n "$testmode"
+      && -n "$(declare -F "buildme.update_check.post.$update_check")" 
       && . <(inline "buildme.update_check.post.$update_check") ]]; then
     built["$*"]=0
     return 0 
   fi
 
-  # if a build function was specified
-  if [[ -n "$(declare -F build)" ]]; then
+  # if a build function was specified and we're not in test mode
+  if [[ -n "$(declare -F build)" && ! -n "$testmode" ]]; then
     # execute the build function in a sub-shell
     ("$build" "$@")
     # memoize result of building this target
     built["$*"]="$?"
 
-    unset -f build
     # update timestamp/checksum for this target
-    if [[ -n "$(declare -F "buildme.update_check.update.$update_check")" ]]; then
+    if [[ ! -n "$phony"
+        && -n "$(declare -F "buildme.update_check.update.$update_check")" ]]; then
       . <(inline "buildme.update_check.update.$update_check")
     fi
   fi
+  unset -f build
 }
 
 # take an argument list and an array called optlist of the form:
@@ -185,7 +242,7 @@ buildme.build () {
 #       'c|optionc=a' "description"
 #       'd|optiond=A' "description" )
 # Create and return an associative array called opts, along with the args list
-function getoptions () {
+getoptions () {
   local args=("$@")
   local lookups
   declare -A lookups
@@ -206,8 +263,6 @@ function getoptions () {
   i=0
   while (( i < "${#args[@]}" )); do
     arg="${args["$i"]}"
-    # shift an opt off the opts array
-    # process each opt
     case "${arg}" in
       -*) # if it's an option, remove it from args list
         unset args["$i"]
@@ -289,7 +344,7 @@ function getoptions () {
 # message displaying the options.
 # The first argument is a message to display before the options list.
 # The second argument is a message to dislay after the options list.
-function usage () {
+usage () {
   echo "$1"
   echo "Usage: "
   local i=0 a aliases desc last optline d
@@ -309,7 +364,7 @@ function usage () {
     case "$last" in
       *=*) 
         case "${last##=}" in 
-          -) optline+=' value';;
+          -) optline+=' value' ;;
           a) optline+=' value ...' ;;
           A) optline+=' key=value ...' ;;
         esac
@@ -325,86 +380,114 @@ function usage () {
   echo "$2"
 }
 
-
-# parse command-line options
-optlist=(
-  'h|help' "display a help message."
-  't|test1=-' "test1 message"
-  'r|test2=a' "test2 message"
-  's|test3=A' "test3 message"
-)
-eval "$(getoptions "$@")" # returns opts, args
-
-if [[ -n "${opts["help"]}" ]]; then
-  usage "$0"
-fi
-
-# find the project directory
-pushd
-directory="$(pwd)"
-while [[ ! -f "$directory/BUILDME" ]]; do
-  cd ..
-  directory="$(pwd)"
-  if [[ "$(pwd)" -eq / ]]; then
-    die "Could not find BUILDME project build file in any parent directory"
-    break;
+build! () {
+  if (( "$#" > 0 )); then
+    # build each specified target
+    for target in "$@"; do
+      buildme.build "$target"
+    done
+  elif [[ -n "$default" ]]; then
+    # build the default target
+    buildme.build "$default"
+  else
+    die "No default target specified in BUILD file"
   fi
-done 
-popd
+}
 
-# set defaults for project variables
-basename=$(basename "$directory")
-name=${${basename%%-}:-project}
-if [[ -f VERSION ]]
-then
-  version=$(cat VERSION)
-fi
-version=${version:-${${basename#-}:-1.0.0}}
+{ # parse command-line options
+  optlist=(
+    'h|help' "display a help message."
+  )
+  eval "$(getoptions "$@")" # returns opts, args
 
-description='unknown project'
-url=''
-license=()
-depends=()
-update_check='mtime' # valid values: mtime, checksum, exists
+  if [[ -n "${opts["help"]}" ]]; then
+    usage "$0"
+    exit 1
+  fi
+}
 
-outputDirectory="${directory}/build"
-sourceDirectory="${directory}/src"
-testDirectory="${directory}/test"
 
-configPath=(/etc/conf.d/buildsh ~/.buildsh)
-pluginPath=(/usr/share/buildsh/plugins ~/.buildsh.d)
+{ # find the project directory
+  pushd
+  directory="$(pwd)"
+  while [[ ! -f "$directory/BUILD" ]]; do
+    cd ..
+    directory="$(pwd)"
+    if [[ "$(pwd)" -eq '/' ]]; then
+      die "Could not find BUILDME project build file in any parent directory"
+    fi
+  done 
+  popd
+}
 
-checksum_prog=md5sum
-declare -A checksums
+{ # set defaults for project variables
+  basename=$(basename "$directory")
+  name=${${basename%%-}:-project}
+  if [[ -f VERSION ]]
+  then
+    version=$(cat VERSION)
+  fi
+  version=${version:-${${basename#-}:-1.0.0}}
 
-log_level=2
+  description='unknown project'
+  url=''
+  license=()
+  depends=()
+  update_check='mtime' # valid values: mtime, checksum, exists
 
-# internal variables
-declare -A built
+  outputDirectory="${directory}/build"
+  sourceDirectory="${directory}/src"
+  testDirectory="${directory}/test"
+
+  installdir="/usr"
+  configPath=(
+    "$installdir/share/buildme/config" 
+    /etc/conf.d/buildme.d 
+    /etc/conf.d/buildme 
+    ~/.buildme.d 
+    ~/.buildme
+    "$directory/buildme.d"
+    )
+
+  checksum_prog=md5sum
+  # target checksums
+  declare -A checksums
+
+  log_level=2 # default log level
+  default_action=build # default action
+  default= # default build target
+  testmode= # test mode (do not build)
+
+  # memoized list of things already built during this run
+  declare -A built
+}
 
 # source all configuration files
-for file in "${configPath[@]}"
-do
-  if [[ -f "$file" ]]
-  then
-    source "$file"
-  fi
-done
-
-# source all found plugins
-for path in "${pluginPath[@]}"
-do
-  if [[ -d "$path" ]]
-  then
-    for file in "$path"/*
-    do
+for path in "${configPath[@]}"; do
+  if [[ -f "$path" ]]; then
+    source "$path"
+  elif [[ -d "$path" ]]; then
+    for file in "$path/*"; do
       source "$file"
     done
   fi
 done
 
-# process arguments
-for target in "${args[@]}"; do
-  buildme.build "$target"
-done
+# source the project file
+source "$directory/BUILD"
+
+# get the action
+if (( "$#" > 0 )); then
+  action="$1"
+else
+  action="$default_action"
+fi
+shift
+
+# call the action with the targets
+if [[ -n "$action" && -n "$(declare -F "$action!")" ]]; then
+  "$action!" "$@"
+else
+  die "Undefined action: \"$action\""
+fi
 
